apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: commondev73/auth-microservice-nest:latest
        env:
        - name: JWT_SECRET
          value: "auth-service-consumer"
        - name: JWT_ACCESS_TOKEN_EXPIRES
          value: "15m"
        - name: JWT_REFRESH_TOKEN_EXPIRES
          value: "30m"
        - name: KAFKA_BROKER
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: KAFKA_CLIENT_ID
          value: "auth-microservice"
        - name: KAFKA_GROUP_ID
          value: "auth-service-consumer"