apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api-gateway
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: api-gateway
subjects:
- kind: ServiceAccount
  name: default
  namespace: api-gateway
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
