apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pisitchai1994/user-microservice-nest:latest
        env:
        - name: MONGO_HOST
          value: "mongo-mongodb.mongo.svc.cluster.local"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          value: "root"
        - name: MONGO_PASSWORD
          value: "root"
        - name: MONGO_DATABASE
          value: "user"
        - name: REDIS_HOST
          value: "redis-master.redis.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "root"
        - name: REDIS_DB
          value: "0"
        - name: KAFKA_BROKER
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: KAFKA_CLIENT_ID
          value: "user-microservice"
        - name: KAFKA_GROUP_ID
          value: "user-service-consumer"