name: Docker Build and Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 

      - name: Login to Docker Hub
        uses: docker/login-action@v2.5.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set Docker target for master
        if: github.ref_name == 'master'
        run: |
          echo "target=prod" >> $GITHUB_ENV
          echo "tag=latest" >> $GITHUB_ENV

      - name: Set Docker target for develop
        if: github.ref_name == 'develop'
        run: |
          echo "target=dev" >> $GITHUB_ENV
          echo "tag=dev" >> $GITHUB_ENV

      - name: Build API Gateway and push Docker image
        uses: docker/build-push-action@v6.15.0 
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          target: ${{ env.target }}
          push: true
          tags: commondev73/api-gateway-nest:${{ env.tag }}

      - name: Build Auth Service and push Docker image
        uses: docker/build-push-action@v6.15.0 
        with:
          context: ./auth-microservice
          file: ./auth-microservice/Dockerfile
          target: ${{ env.target }}
          push: true
          tags: commondev73/auth-microservice-nest:${{ env.tag }}    

      - name: Build User Service and push Docker image
        uses: docker/build-push-action@v6.15.0 
        with:
          context: ./user-microservice
          file: ./user-microservice/Dockerfile
          target: ${{ env.target }}
          push: true
          tags: commondev73/user-microservice-nest:${{ env.tag }}
